// <auto-generated />
namespace Project.identityMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "202211281259185_addOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
